
-- USER is a reserved keyword with Postgres
-- You must use double quotes in every query that user is in:
-- ex. SELECT * FROM "user";
-- Otherwise you will have errors!
CREATE TABLE "user" (
    "id" SERIAL PRIMARY KEY,
    "username" VARCHAR (80) UNIQUE NOT NULL,
    "password" VARCHAR (1000) NOT NULL
);

Create table "data"(
	"id"  SERIAL PRIMARY KEY,
	"title" VARCHAR(120) NOT NULL,
	"japanese" VARCHAR(120) NOT NULL,
	"english" VARCHAR(120) NOT NULL,
	"key" VARCHAR(120) NOT NULL);
    
INSERT INTO "data" ("title","japanese","english","key") VALUES ('hiragana_quiz','あ','a','vowel'),
('hiragana','い','i','vowel'),
('hiragana','う','u','vowel'),
('hiragana','え','e','vowel'),
('hiragana','お','o','vowel'),
('hiragana','か','ka','k'),
('hiragana','き','ki','k'),
('hiragana','く','ku','k'),
('hiragana','け','ke','k'),
('hiragana','こ','ko','k'),
('hiragana','さ','sa','s'),
('hiragana','し','shi','s'),
('hiragana','す','su','s'),
('hiragana','せ','se','s'),
('hiragana','そ','so','s'),
('hiragana','た','ta','t'),
('hiragana','ち','chi','t'),
('hiragana','つ','tsu','t'),
('hiragana','て','te','t'),
('hiragana','と','to','t'),
('hiragana','な','na','n'),
('hiragana','に','ni','n'),
('hiragana','ぬ','nu','n'),
('hiragana','ね','ne','n'),
('hiragana','の','no','n'),
('hiragana','は','ha','h'),
('hiragana','ひ','hi','h'),
('hiragana','ふ','fu','h'),
('hiragana','へ','he','h'),
('hiragana','ほ','ho','h'),
('hiragana','ま','ma','m'),
('hiragana','み','mi','m'),
('hiragana','む','mu','m'),
('hiragana','め','me','m'),
('hiragana','も','mo','m'),
('hiragana','や','ya','y'),
('hiragana','ゆ','yu','y'),
('hiragana','よ','yo','y'),
('hiragana','ら','ra','r'),
('hiragana','り','ri','r'),
('hiragana','る','ru','r'),
('hiragana','れ','re','r'),
('hiragana','ろ','ro','r'),
('hiragana','わ','wa','w'),
('hiragana','を','wo','w'),
('hiragana','ん','n','n'),
('katakana','ア','a','vowel'),
('katakana','イ','i','vowel'),
('katakana','ウ','u','vowel'),
('katakana','エ','e','vowel'),
('katakana','オ','o','vowel'),
('katakana','カ','ka','k'),
('katakana','キ','ki','k'),
('katakana','ク','ku','k'),
('katakana','ケ','ke','k'),
('katakana','コ','ko','k'),
('katakana','サ','sa','s'),
('katakana','シ','shi','s'),
('katakana','ス','su','s'),
('katakana','セ','se','s'),
('katakana','ソ','so','s'),
('katakana','タ','ta','t'),
('katakana','チ','chi','t'),
('katakana','ツ','tsu','t'),
('katakana','テ','te','t'),
('katakana','ト','to','t'),
('katakana','ナ','na','n'),
('katakana','ニ','ni','n'),
('katakana','ヌ','nu','n'),
('katakana','ネ','ne','n'),
('katakana','ノ','no','n'),
('katakana','ハ','ha','h'),
('katakana','ヒ','hi','h'),
('katakana','フ','fu','h'),
('katakana','ヘ','he','h'),
('katakana','ホ','ho','h'),
('katakana','マ','ma','m'),
('katakana','ミ','mi','m'),
('katakana','ム','mu','m'),
('katakana','メ','me','m'),
('katakana','モ','mo','m'),
('katakana','ヤ','ya','y'),
('katakana','ユ','yu','y'),
('katakana','ヨ','yo','y'),
('katakana','ラ','ra','r'),
('katakana','リ','ri','r'),
('katakana','ル','ru','r'),
('katakana','レ','re','r'),
('katakana','ロ','ro','r'),
('katakana','ワ','wa','w'),
('katakana','ヲ','wo','w'),
('katakana','ン','n','n');